### ISSUE TITLE
/venues/GEN Fails to load 

### ISSUE THREAD

**Issue by ImJustChew** [nthumodifications/courseweb#21]
**Describe the bug**
TypeError: Cannot read properties of undefined (reading 'map')
    at /var/task/.next/server/chunks/2702.js:1:1193
    at Array.forEach (<anonymous>)
    at /var/task/.next/server/chunks/2702.js:1:1116
    at Array.forEach (<anonymous>)
    at r (/var/task/.next/server/chunks/2702.js:1:1087)
    at q (/var/task/.next/server/app/[lang]/venues/[locationId]/page.js:1:2255)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '2245657393'
}

**To Reproduce**
1. Go to nthumods.com/venues/GEN

**Expected behavior**
Supposed to not crash

**Additional context**

**Comment by ImJustChew** [comment]
GEN might have been a bad parsing of the venues, it's now missing.
